### ISSUE TITLE
Warning about sample with new version of ggplot2

### ISSUE THREAD

**Issue by stamats** [aloy/qqplotr#12]
I use R 4.2.2 Patched (2022-11-12 r83339), ggplot2 version 3.4.0 (2022-11-04) and qqplotr 0.0.5 (2021-04-23). 

Running your example:
smp <- data.frame(norm = rnorm(100))
gg <- ggplot(data = smp, mapping = aes(sample = norm)) +
    stat_qq_band() +
    stat_qq_line() +
    stat_qq_point() +
    labs(x = "Theoretical Quantiles", y = "Sample Quantiles")
gg

I now get two warnings:

1: The following aesthetics were dropped during statistical transformation: sample
ℹ This can happen when ggplot fails to infer the correct grouping structure in the data.
ℹ Did you forget to specify a `group` aesthetic or to convert a numerical variable into a
  factor? 
2: The following aesthetics were dropped during statistical transformation: sample
ℹ This can happen when ggplot fails to infer the correct grouping structure in the data.
ℹ Did you forget to specify a `group` aesthetic or to convert a numerical variable into a
  factor?

Which are from stat_qq_band and stat_qq_line. That is

ggplot(data = smp, mapping = aes(sample = norm)) +  stat_qq_band()

and 

ggplot(data = smp, mapping = aes(sample = norm)) +  stat_qq_line()

give a warning, but not

ggplot(data = smp, mapping = aes(sample = norm)) +  stat_qq_point() 

I have to admit that I'm not sure whether it is an issue with your package or ggplot2.

Best wishes
Matthias

**Comment by stamats** [comment]
see also https://github.com/tidyverse/ggplot2/issues/5053

**Comment by stamats** [comment]
I added dropped_aes = c("sample") to stat_pp_band, stat_pp_line, stat_qq_band, stat_qq_line in a fork of your repository and the warnings disappeared. 
Best Matthias

**Comment by stamats** [comment]
I have generated a PR.
Best Matthias

**Comment by rempsyc** [comment]
@aloy any plans to submit the new version to CRAN? FYI I have to wait for that to submit the new version of `rempsyc` and I'm sure it's the same for your other reverse dependencies.

**Comment by aloy** [comment]
@rempsyc , I plan to submit to CRAN today or tomorrow.
