### ISSUE TITLE
The colors and fill colors do not match

### ISSUE THREAD

**Issue by GegznaV** [aloy/qqplotr#2]
Consider this code, which is basically one of the examples in `qqpotr` package with `color = "black"` added:

```r
library(qqplotr)
data("barley", package = "lattice")

gg <- ggplot(data = barley, mapping = aes(sample = yield, color = site, fill = site)) +
    stat_qq_band(alpha=0.5) +
    stat_qq_line(color = "black") +
    stat_qq_point() +
    facet_wrap(~ site) +
    labs(x = "Theoretical Quantiles", y = "Sample Quantiles")
gg
```
The colors and fill colors do not match any more as additional (unwanted) color "#4D4D4D" (grey shade) appears in the list.

![image](https://user-images.githubusercontent.com/12725868/49556660-89683880-f90d-11e8-84a2-45e20aead3e7.png)

How can this be fixed?

**Comment by aloy** [comment]
@GegznaV this is definitely a bug in the implementation. We'll start working on a fix.

@almeidaxan Can you take a look too? We may need to add geoms for each of these...

**Comment by GegznaV** [comment]
Any news on fixing this issue?

**Comment by aloy** [comment]
Hi @GegznaV,

If you want the lines to be the same color as the points, this works:

```
ggplot(data = barley, mapping = aes(sample = yield, fill = site, color = site)) +
	stat_qq_band(alpha=0.5) +
	stat_qq_line() +
	stat_qq_point() +
	facet_wrap(~ site) +
	labs(x = "Theoretical Quantiles", y = "Sample Quantiles")
```

We're looking into why things go awry if you want the lines to be black. Sorry that this slipped through the cracks!

**Comment by aloy** [comment]
@GegznaV - fixed

**Comment by GegznaV** [comment]
Nice!
