### ISSUE TITLE
The places of `data` and `mapping` should be swithed

### ISSUE THREAD

**Issue by GegznaV** [aloy/qqplotr#4]
By convention in `ggplot2`, the first argument in 'geom' and 'stat' functions is *mapping* and the second is *data* (see figure below). And in `qqplotr` these arguments are switched. It makes inconvenient to use additional aesthetics without a new dataset as `mapping` must be written every time.

1) Is there a reason, why in `qqplotr` the places of these two arguments are swithed?
2) Can this issue be fixed to follow the `ggplot2` convention?

![image](https://user-images.githubusercontent.com/12725868/56165707-5846f580-5fdc-11e9-967c-43fece015b71.png)
![image](https://user-images.githubusercontent.com/12725868/56165727-63018a80-5fdc-11e9-819c-6aac87e7766a.png)

**Comment by aloy** [comment]
@GegznaV, I agree—thanks for catching this bug! I will put this on my TODO list.
