### ISSUE TITLE
Maintainership

### ISSUE THREAD

**Issue by aloy** [aloy/qqplotr#5]
@almeidaxan,

Do you want to remain the maintainer of the package, or do you want to transfer this to me? I have some updates to make soon, so it's a natural time to revisit this.

**Comment by almeidaxan** [comment]
Hi @aloy. Sorry for my long hiatus.

I prefer transferring the maintainership to you. Right now I'm not unable to give qqplotr enough attention 😔.

Please let me know if you need anything from me to formalize this transfer (e.g., on CRAN).

**Comment by aloy** [comment]
@almeidaxan , I am submitting an update to CRAN, so be prepared for them to ask you about maintainership.
