### ISSUE TITLE
Feature request: Downsample data in qq-plot

### ISSUE THREAD

**Issue by jdstamp** [aloy/qqplotr#9]
Hi,

I really like `qqplotr` and I am trying to use it on some of my data. The problem that I am running into is that the data that I want to plot has approximately 2 Mio. data points. The pdf I get by saving it as `ggsave(file, device = "pdf")` has 2.7Mb but when loading it, it seems to set every single data point separately and thus takes about 2 minutes to load in a standard pdf viewer.

Do you think it would be possible to e.g. offer a feature to downsample the data that is plotted without changing the overall distribution in the plot?

**Comment by aloy** [comment]
Hi @jdstamp,

I saw your pull request, and I also saw that you said it wasn't working for your data set. I just made a first pass at this based on a downsampling implementation in the `opdisDownsampling` package. I haven't tweaked things yet for speed, but I thought you could give some feedback.

Here's an example with the new version:

```
smp <- data.frame(x = rgamma(1e6, 5, 2)

ggplot(data = smp, mapping = aes(sample = x)) +
   stat_qq_point(down.sample = 250)
```

It can be slow, but I'll add parameters to allow parallel processing and some control of the way the algorithm works.

**Comment by jdstamp** [comment]
Hi @aloy ,

I forgot about this issue for a long time. I am sorry I never got back to you about it.

The solution above does not work for me. I found a workaround that is hacky:
```
ggall <- tib %>% ggplot(mapping = aes(
    sample = log_transformed,
    color = trt,
    fill = trt
  )) +
    theme_bw() +
    scale_fill_brewer(palette="Dark2") +
    scale_color_brewer(palette="Dark2") +
    stat_qq_band(distribution = di,
                 detrend = de,
                 alpha = 0.5) +
    stat_qq_line(distribution = di, detrend = de) +
    stat_qq_point(distribution = di, detrend = de) +
    facet_grid(cor ~ trt) +
    theme(legend.position = "none") +
    labs(x = "Theoretical Quantiles -log$_{10}(p)$", y = "Sample Quantiles -log$_{10}(p)$")
  ggbuilt <- ggplot_build(ggall)
  ggdat1 <- ggbuilt$data[[1]]
  ggdat2 <- ggbuilt$data[[2]]
  ggdat3 <- ggbuilt$data[[3]]
  downsampled1 <- ggdat1 %>%
    filter(x > 2 | row_number() %% 10 == 0) %>%
    filter(x > 3 | row_number() %% 10 == 0) %>%
    filter(x > 4 | row_number() %% 10 == 0) 
  downsampled3 <- ggdat3 %>%
    filter(x > 2 | row_number() %% 10 == 0) %>%
    filter(x > 3 | row_number() %% 10 == 0) %>%
    filter(x > 4 | row_number() %% 10 == 0)
  ggbuilt$data <- list(downsampled1, ggdat2, downsampled3)
  gg <- ggplot_gtable(ggbuilt)
  plot(gg)
```

The reason I do this in steps is that on the log-transformed scale, most points are crowded at low numbers and the plot appearance did not change doing the above.

However, I found another solution to the problem that unfortunately does not work with stat_qq_point:
https://cran.r-project.org/web/packages/ggrastr/vignettes/Raster_geoms.html

This turns out to be the best way of dealing with many data points for me. 

Is the `geom_point_rast` function maybe something, that could be easily integrated?

**Comment by aloy** [comment]
Hi @jdstamp ,

Did you try the rasterize function from `{ggrastr}`? That works for me when I wrap it around the point layer:

```
rasterize(stat_qq_point(distribution = di, detrend = de))
```

**Comment by jdstamp** [comment]
Hi @aloy ,

Yes, that is what seems to working best! Thank you!

This issue can be closed with this solution.
